name: Compilation
'on':
  - push

env:
  LUABITOP_VERSION: "1.0.2"
  WIRESHARK_VERSION: "4.0.10"
  LUA_VERSION: "5.2.4"

jobs:
  Build_Windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      ## Get all source archives
      - name: Get LuaBitOp
        run: Invoke-WebRequest -Uri http://bitop.luajit.org/download/LuaBitOp-${env:LUABITOP_VERSION}.zip -OutFile dll.zip
      - name: Get Wireshark
        run: Invoke-WebRequest -Uri  https://2.na.dl.wireshark.org/win64/Wireshark-win64-${env:WIRESHARK_VERSION}.exe -OutFile wireshark.exe
      - name: Get Lua
        run: Invoke-WebRequest -Uri  https://www.lua.org/ftp/lua-${env:LUA_VERSION}.tar.gz -OutFile lua.tar.gz

      ## Extract / rename folders and delete downloads
      - name: Unzip DLL source code
        run: tar -xf dll.zip
      - name: Normalize DLL source code folder
        run: mv LuaBitOp* dll
      - name: Delete DLL source code archive
        run: rm dll.zip
      - name: Unzip Lua source code
        run: tar -xf lua.tar.gz
      - name: Normalize Lua source code folder
        run: mv lua-* lua
      - name: Delete Lua source code archive
        run: rm lua.tar.gz
      - name: Extract lua52.dll from wireshark.exe
        run: 7z e wireshark.exe lua52.dll
      - name: Rename Lua DLL with the right name for the build
        run: mv lua52.dll lua51.dll
      - name: Delete Wireshark executable
        run: rm wireshark.exe

      ## Copy everything in build directory (dll) and compile
      - name: Copy Lua Source code to build directory
        run: cp lua\src\* dll
      - name: Compile
        run: cd dll && mingw32-make -f Makefile.mingw

      ## Archive dll for download
      - name: Archive DLL as artifact
        uses: actions/upload-artifact@v3
        with:
          name: luabitop
          path: dll/bit.dll
          if-no-files-found: error

      ## Release on tag
      - name: Release DLL
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dll/bit.dll
          fail_on_unmatched_files: true
